// leave off @2x/@3x
const images = {
  api: require('../images/icons/icon-api-testing.png'),
  backButton: require('../images/icons/back-button.png'),
  backgroundSolid: require('../images/BG-solid.png'),
  buttonBackground: require('../images/button-bg.png'),
  chevronRight: require('../images/icons/chevron-right.png'),
  closeButton: require('../images/icons/close-button.png'),
  components: require('../images/icons/icon-components.png'),
  deviceInfo: require('../images/icons/icon-device-information.png'),
  faq: require('../images/icons/faq-icon.png'),
  hamburger: require('../images/icons/hamburger.png'),
  home: require('../images/icons/icon-home.png'),
  ignite: require('../images/ignite_logo.png'),
  igniteClear: require('../images/ignite-logo-transparent.png'),
  launch: require('../images/launch-icon.png'),
  logo: require('../images/logo.png'),
  logoClear: require('../images/top_logo.png'),
  logoIcon: require('../images/logo-icon.png'),
  logoIconSmall: require('../images/logo-icon-sm.png'),
  logoIconWhite: require('../images/logo-icon-white.png'),
  logoIconTypeColor: require('../images/logo-icon-type-color.png'),
  logoIconTypeColorHorizontal: require('../images/logo-icon-type-color-horizontal.png'),
  ready: require('../images/your-app.png'),
  theme: require('../images/icons/icon-theme.png'),
  tileBg: require('../images/tile_bg.png'),
  usageExamples: require('../images/icons/icon-usage-examples.png'),
  snapshot: require('../images/snapshot.jpg'),
  user: require('../images/user.png'),
  marker_red: require('../images/marker_red.png'),
  marker_yellow: require('../images/marker_yellow.png'),
  marker_green: require('../images/marker_green.png'),
}

export default images
